<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="com.Sauce.Reporting.ExtentTestListener"/>
    <listener class-name="com.Sauce.TestUtils.RetryListener"/>
  </listeners>
  <test thread-count="2" name="Test(failed)">
    <classes>
      <class name="com.Sauce.Tests.TC_Sauce_TestFilterNameAtoZ">
        <methods>
          <include name="tearDown"/>
          <include name="test_FilterNameAtoZ"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.Sauce.Tests.TC_Sauce_TestFilterNameAtoZ -->
      <class name="com.Sauce.Tests.TC_Sauce_TestFilterNameZtoA">
        <methods>
          <include name="setUp"/>
          <include name="tearDown"/>
          <include name="testHere"/>
        </methods>
      </class> <!-- com.Sauce.Tests.TC_Sauce_TestFilterNameZtoA -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
